name: Build LaTeX and Save PDF to root

on:
  push:
    branches: [main]

permissions:
  contents: write  # git push 허용

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Copy PDF to root for GitHub Pages
        run: cp main.pdf cv.pdf

      - name: Commit and push PDF to main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git add cv.pdf
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update PDF"
            git rebase origin/main
            git push
          fi
